apiVersion: apps/v1
kind: Deployment
metadata:
  name: zack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zack
  template:
    metadata:
      labels:
        app: zack
    spec:
      containers:
      - image: gcr.io/halyard-269216/go-docker
        ports:
        - containerPort: 80
